#!/usr/bin/env -S deno run --allow-read --allow-write 

/**
 * Reads all binary files (files without a file extension) from the ../bin/ directory,
 * converts them to base64, and writes one TypeScript module per binary to ../bin/
 * (e.g. bin/log-darwin-arm64.ts), each exporting a single default string.
 */

const scriptDir = new URL(".", import.meta.url).pathname
const binDir = `${scriptDir}../bin`

const written: string[] = []

for await (const entry of Deno.readDir(binDir)) {
  if (!entry.isFile) continue
  // Skip previously-generated .ts files
  if (entry.name.endsWith(".ts")) continue

  const filePath = `${binDir}/${entry.name}`
  const bytes = await Deno.readFile(filePath)

  // Encode binary data to base64 using built-in btoa
  let binary = ""
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i])
  }
  const base64 = btoa(binary)

  const outFile = `${binDir}/${entry.name}.ts`

  const lines: string[] = [
    "// AUTO-GENERATED by deno/scripts/bin-to-base64.ts — do not edit manually",
    "// Do not edit this file directly. To regenerate, run:",
    "//   deno/scripts/bin-to-base64.ts",
    "//",
    "// Usage:",
    `//   import bin from "./bin/${entry.name}.ts"`,
    "//",
    "//   const bytes = Uint8Array.from(atob(bin), (c) => c.charCodeAt(0))",
    "",
    `const bin = "${base64}"`,
    "",
    "export default bin",
    "",
  ]

  await Deno.writeTextFile(outFile, lines.join("\n"))
  written.push(entry.name)
}

written.sort()
console.log(`Wrote ${written.length} binary modules:`)
for (const name of written) {
  console.log(`  bin/${name}.ts`)
}
