#!/usr/bin/env -S deno run --allow-read --allow-write 

/**
 * Reads all binary files (files without a file extension) from the ../bin/ directory,
 * converts them to base64, and writes a TypeScript module to ../bin.ts that exports
 * an object mapping file names to their base64-encoded contents.
 */

const scriptDir = new URL(".", import.meta.url).pathname
const binDir = `${scriptDir}../bin`
const outFile = `${scriptDir}../bin/bin.ts`

const entries: Record<string, string> = {}

for await (const entry of Deno.readDir(binDir)) {
  if (!entry.isFile) continue

  const filePath = `${binDir}/${entry.name}`
  const bytes = await Deno.readFile(filePath)

  // Encode binary data to base64 using built-in btoa
  let binary = ""
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i])
  }
  entries[entry.name] = btoa(binary)
}

const sortedKeys = Object.keys(entries).sort()

const lines: string[] = [
  "// AUTO-GENERATED by deno/scripts/bin-to-base64.ts — do not edit manually",
  "// Do not edit this file directly. To regenerate, run:",
  "//   deno/scripts/bin-to-base64.ts",
  "//",
  "// Usage:",
  '//   import bins from "./bin/bin.ts"',
  "//",
  '//   const base64 = bins["log-darwin-arm64"]',
  "//   const bytes = Uint8Array.from(atob(base64), (c) => c.charCodeAt(0))",
  "",
  "const bins: Record<string, string> = {",
]

for (const key of sortedKeys) {
  lines.push(`  "${key}": "${entries[key]}",`)
}

lines.push("}")
lines.push("")
lines.push("export default bins")
lines.push("")

await Deno.writeTextFile(outFile, lines.join("\n"))

console.log(`Wrote ${sortedKeys.length} binaries to ${outFile}`)
