on: 
  push:
    branches: [main]
  # This tool encourages you to run it on pull requests to test the deployment process.
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # If your deploy script that you write needs to push a git commit, git tag, or create a GitHub Release.
      pull-requests: write # If you enable pull request comments (they are enabled by default).
      id-token: write # required by jsr and npm for publishing package 
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up tools
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      
      - uses: levibostian/decaf@672d4ed6704faecd9ab58cb44255f9f16af34f49 # 0.15.0
        env:
          # required to use 'gh' CLI in my step scripts. 
          GH_TOKEN: ${{ github.token }}      
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          get_latest_release_current_branch: deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases get
          get_next_release_version: deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits
          deploy: |
            make build-all
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-jsr --package-path ./deno --allow-dirty
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases set-assets "dist/bin-x86_64-Linux" "dist/bin-aarch64-Linux" "dist/bin-x86_64-Darwin" "dist/bin-aarch64-Darwin" "dist/bin-x86_64-Windows.exe" "dist/bin-aarch64-Windows.exe"
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases set 