on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: jdx/mise-action@v3

    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: Run tests
      run: |
        make test-junit

    - name: Run CLI to see how it's going to look like
      run: ./tests/scripts/test-cli.sh

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: reports/junit.xml

    - name: Annotate failed tests
      if: always() # Run with test/lint failures.
      uses: granodigital/report-annotate@v1.0.1
      with:
        reports: |
          junit|reports/junit.xml
