on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.43.1 

    # the go asdf plugin requires you call reshim after 'go install' to make new CLIs available in path. 
    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest && asdf reshim golang

    - name: Run tests
      run: |
        make test-junit

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: junit-results-${{ matrix.os }}
        path: reports/junit.xml

    - name: Annotate failed tests
      if: always() # Run with test/lint failures.
      uses: granodigital/report-annotate@v1.0.1
      with:
        reports: |
          junit|reports/junit.xml
