on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Set up Go
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4

    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: Run tests
      run: |
        make test-junit

    - name: Run CLI to see how it's going to look like
      run: ./tests/scripts/test-cli.sh

    - name: Upload test results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: junit-results
        path: reports/junit.xml

    - name: Annotate failed tests
      if: always() # Run with test/lint failures.
      uses: granodigital/report-annotate@8443be89f9109669a14c838c42bc5fd08830cd6f # v3.3.4
      with:
        reports: |
          junit|reports/junit.xml
